#!/bin/bash

LOAD=$(cat /proc/loadavg | cut -d '.' -f 1)

if [ "$LOAD" -gt "$((4))" ] ; then
	exit 1
fi

if [ ! -s /var/cache/motd-glsa ] ; then
	umask 0377
	echo updating > /var/cache/motd-glsa
	/usr/local/sbin/check-updates > /var/cache/motd-glsa
fi
     
cat /var/cache/motd-glsa
